//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Cv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class about
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string description { get; set; }
        public string picture { get; set; }
    }
}
