//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Cv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class educations
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string subtitle_1 { get; set; }
        public string subtitle_2 { get; set; }
        public string score { get; set; }
        public string date { get; set; }
    }
}
