//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Cv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_CvEntities4 : DbContext
    {
        public db_CvEntities4()
            : base("name=db_CvEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about> about { get; set; }
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<communication> communication { get; set; }
        public virtual DbSet<educations> educations { get; set; }
        public virtual DbSet<certificates> certificates { get; set; }
        public virtual DbSet<experinces> experinces { get; set; }
        public virtual DbSet<hobbies> hobbies { get; set; }
        public virtual DbSet<talents> talents { get; set; }
    }
}
